'use-strict'
/**
 * Utility functions to ease getting date and time for the calendar bar.
*/

const dayNames = [ "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const monthNames = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
];


/**
 * Utility to determine if a given year is a leap year.
 * @param {Number} year year as returned by Date.getFullYear.
 * @returns {boolean} True if year has 366 days.
 */
export const isLeapYear = function(year)
{
    return ((year % 4 == 0) && (year % 100 != 0)) || (year % 400 == 0);
}

/**
 * Returns the number of days in a given month for the current year.
 * @param {Number} monthNum Number as returned by Date.getMonth.
 * @returns {Number} Value between [0 - 31]
 */
export const numDays = function(monthNum) {
    const numDaysMap = [
        31,
        (isLeapYear(new Date().getFullYear)) ? 29 : 28,
        31,
        30,
        31,
        30,
        31,
        31,
        30,
        31,
        30,
        31     
    ];
    
    // These functions let the caller do something like 0 - 1 in the argument
    if (Math.abs(monthNum) > 11) monthNum %= 12
    if (monthNum < 0) monthNum = 11 + monthNum;

    return numDaysMap[monthNum];
}

/**
 * Returns a week object that associates a day in the current week with the days of the current month.
 * @returns {Object}
 */
export const getCurrentWeek = function() {
    let today = new Date();
    
    let sundayDate = today.getDate() - today.getDay();
    let weekDates = [ 0, 0, 0, 0, 0, 0, 0 ];

    if (sundayDate < 0) {
        let prevMonthDays = numDays(today.getMonth() - 1);
        weekDates[0] = prevMonthDays - sundayDate + 1;
    } else {
        weekDates[0] = sundayDate;
    }

    let currentMonthDays = numDays(today.getMonth());
    for (let a = 1; a < weekDates.length; a++) {
        weekDates[a] = weekDates[a - 1] + 1;
        if (weekDates[a] > currentMonthDays) {
            weekDates[a] = 1;
        }
    }

    return {
        month: monthNames[today.getMonth()],
        week: weekDates
    };
}

/**
 * Generates an array of week-aligned days for a given month and year. Defaults to current date if no month/year given.
 * @param {Number?} month Value returned by Date.getMonth()
 * @param {Number?} year Value returned by Date.getFullYear()
 * @return {Array} An array of length 42 where index-0 is on a Saturday and 41 is on a Sunday. Elements < 0 indicate days on different months.
 */
export const getMonthGrid = function(month, year) {
    let dateGrid = new Array(42);

    let first = new Date();
    first.setDate(1);
    
    // Check optional args
    if (month)
        first.setMonth(month);
    if (year)
        first.setFullYear(year);

    let prevMonth = (first.getMonth() - 1 >= 0) ? first.getMonth() - 1: 11;
    let prevMonthDayCount = numDays(prevMonth) + 1;

    for(let a = 0; a < first.getDay(); a++) {
        dateGrid[a] = (prevMonthDayCount - (first.getDay() - a)) * -1;
    }
    
    // Tracks the number of days outside the main month
    let dayCounter = 1;
    for(let a = first.getDay(); a < dateGrid.length; a++) {
        if (dayCounter <= numDays(first.getMonth()) && dayCounter > 0) {
            dateGrid[a] = dayCounter++;
        } else {
            if (dayCounter > 0) {
                dayCounter = -1
            };
            dateGrid[a] = dayCounter--;
        }
    }

    return dateGrid;
}

/**
 * Returns a month string corresponding to the 0-indexed number given.
 * @param {Number} monthCode Integer in the range [0, 11]
 * @returns Capitalized month.
 */
export const getMonthName = function(monthCode) {
    if (monthCode > monthNames.length) return null;
    
    return monthNames[monthCode];
}

/**
 * Calculates the number weeks spanned by a grid of months gien.
 * @param {Array[42]} monthArray Array generated by {@link getMonthGrid}.
 * @returns 0 if the given array has length != 42. Otherwise returns 4, 5, or 6.
 */
export const getWeekSpan = function(monthArray) {
    if (monthArray.length != 42) return 0;
    if (monthArray[35] > 0) return 6;
    if (monthArray[28] > 0) return 5;
    return 4;
}

/**
 * Calculates which row of the month grid a given date is on.
 * @param {Array<Number>} monthArray Array returned by {@link getMonthGrid}.
 * @param {Number} date
 * @return {Number} [0 - 5] if the date is valid, -1 otherwise.
 */
export const getWeekRow = function(monthArray, date) {
    let dayIndex = 0;
    while (monthArray[dayIndex] != monthArray[date] && dayIndex < monthArray.length) {
        dayIndex++;
    } 
    if (dayIndex >= monthArray.length) return -1;
    else {
        return Math.floor(dayIndex / 7);
    }
}

/**
 * Generate string in YYYYMMDD format from a Date object.
 * @param {Date} date 
 */
export const dateISOString = function(date) {
    const m = date.getMonth();
    const d = date.getDate();
    let ms = (m < 9) ? "0".concat(m + 1): m + 1;
    let ds = (d < 9) ? "0".concat(d + 1): d + 1;
    return `${date.getFullYear()}${ms}${ds}`;
}